# This workflow builds the project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code base
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v2
        with:
          cache: 'maven'
          check-latest: true
          distribution: 'adopt'
          java-version: 11

      - name: Prepare Maven cache
        # https://github.com/actions/cache
        uses: actions/cache@v3.2.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Verify artifacts
        run: mvn -B -Psonatype-snapshot-repository verify
