# This workflow builds the project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code base
        # https://github.com/actions/checkout
        uses: actions/checkout@v2.3.3

      - name: Prepare Maven artifact cache
        # https://github.com/actions/cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 1.8

      - name: Verify artifacts
        run: mvn -B verify
